/*
 *  @file  : IcdCrcCalcToolDlg.h
 *  @author: luteng
 *  @date  : 2015-05-27 15:24:29.977
 *  @note  : Generated by SlxTemplates
 */

// IcdCrcCalcToolDlg.h : header file
//

#include "afxcmn.h"
#if !defined(AFX_ICDCRCCALCTOOLDLG_H__0A887380_C071_4C4B_8A5B_47199C0EF4E7__INCLUDED_)
#define AFX_ICDCRCCALCTOOLDLG_H__0A887380_C071_4C4B_8A5B_47199C0EF4E7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <vector>

enum IcdFileStatus
{
    IFS_DEALING,
    IFS_SUCCESS,
    IFS_FAILED,
};

struct IcdInfo
{
    TCHAR szFilePath[MAX_PATH];
    TCHAR szNewFilePath[MAX_PATH];
    IcdFileStatus nStatus;
    TCHAR szErrorMessage[1024];
    TCHAR szHeaderVersion[MAX_PATH];
    TCHAR szIedType[MAX_PATH];
    TCHAR szCustomFunction[MAX_PATH];
    TCHAR szCrc[MAX_PATH];
};

/////////////////////////////////////////////////////////////////////////////
// CIcdCrcCalcToolDlg dialog

class CIcdCrcCalcToolDlg : public CDialog
{
// Construction
public:
	CIcdCrcCalcToolDlg(CWnd* pParent = NULL);	// standard constructor
    virtual ~CIcdCrcCalcToolDlg();

// Dialog Data
	//{{AFX_DATA(CIcdCrcCalcToolDlg)
	enum { IDD = IDD_ICDCRCCALCTOOL_DIALOG };
		// NOTE: the ClassWizard will add data members here
	//}}AFX_DATA

	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CIcdCrcCalcToolDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:
    HICON m_hIcon;
    HACCEL m_hAccel;
    std::vector<IcdInfo> m_vectorIcds;
    HANDLE m_hSemphore;
    HANDLE m_hStopEvent;
    HANDLE m_hDealThread;

    void StartDealThread();
    void StopDealThread();

    static DWORD CALLBACK DealProc(LPVOID lpParam);

    void ShowFile(int nItemIndex);
    void DoImportFiles(const CStringArray &strPaths);

    static CString CalcNewFilePath(LPCTSTR lpOldFilePath, LPCTSTR lpCrc, LPCTSTR lpHeaderVersion = TEXT(""), LPCTSTR lpIedType = TEXT(""), LPCTSTR lpCustomFunction = TEXT(""));

	// Generated message map functions
	//{{AFX_MSG(CIcdCrcCalcToolDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnPaint();
	afx_msg HCURSOR OnQueryDragIcon();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
public:
    CListCtrl m_listFiles;
    afx_msg void OnNMRClickList(NMHDR *pNMHDR, LRESULT *pResult);
protected:
    virtual BOOL OnCommand(WPARAM wParam, LPARAM lParam);
public:
    afx_msg void OnClose();
    afx_msg void OnNMDblclkList(NMHDR *pNMHDR, LRESULT *pResult);
    afx_msg void OnSize(UINT nType, int cx, int cy);
protected:
    virtual LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam);
public:
    afx_msg void OnDropFiles(HDROP hDropInfo);
    virtual BOOL PreTranslateMessage(MSG* pMsg);
    afx_msg void OnBnClickedBtnimport();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ICDCRCCALCTOOLDLG_H__0A887380_C071_4C4B_8A5B_47199C0EF4E7__INCLUDED_)
