/*
 *  @file  : IcdCrcCalcTool.h
 *  @author: luteng
 *  @date  : 2015-05-27 15:24:29.977
 *  @note  : Generated by SlxTemplates
 */

// IcdCrcCalcTool.h : main header file for the ICDCRCCALCTOOL application
//

#if !defined(AFX_ICDCRCCALCTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_)
#define AFX_ICDCRCCALCTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

/////////////////////////////////////////////////////////////////////////////
// CIcdCrcCalcToolApp:
// See IcdCrcCalcTool.cpp for the implementation of this class
//

class CIcdCrcCalcToolApp : public CWinApp
{
public:
	CIcdCrcCalcToolApp();

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CIcdCrcCalcToolApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CIcdCrcCalcToolApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ICDCRCCALCTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_)
