/*
 *  @file  : stdafx.cpp
 *  @author: luteng
 *  @date  : 2015-05-27 15:24:29.977
 *  @note  : Generated by SlxTemplates
 */

// stdafx.cpp : source file that includes just the standard includes
//	IcdCrcCalcTool.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information

#include "stdafx.h"



